# Generated by Django 5.0.10 on 2026-02-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sizesearch',
            name='chat_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sizesearch',
            name='source',
            field=models.TextField(default='unknown'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
