# Generated by Django 5.0.10 on 2026-02-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_alter_message_chat_id_alter_sizesearch_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
