# Generated by Django 5.0.10 on 2026-02-22 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0003_user_paid_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, unique=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('stars_paid', models.IntegerField(default=0)),
                ('currency', models.CharField(default='XTR', max_length=8)),
                ('payload', models.CharField(blank=True, default='', max_length=128)),
                ('telegram_payment_charge_id', models.TextField(blank=True, default='')),
                ('provider_payment_charge_id', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='paid_until',
        ),
    ]
