# Generated by Django 5.0.10 on 2026-02-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0005_delete_subscription_user_last_payment_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('event_type', models.CharField(choices=[('subscribe_click', 'Subscribe click'), ('successful_payment', 'Successful payment'), ('admin_grant', 'Admin grant'), ('admin_revoke', 'Admin revoke')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=8, null=True)),
                ('charge_id', models.TextField(blank=True, null=True)),
                ('payload', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_payment_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_payment_currency',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_payment_total_amount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_stars_charge_id',
        ),
    ]
